### ISSUE TITLE
Cant Install Plugins

### ISSUE THREAD

**Issue by ethanfox** [Budibase/plugins#50]
Every time try to install a plugin I get this error:  

**Failed to add plugin: Failed to import plugin: Only component plugins are supported outside of self-host.**

You guys don't make it very clear how to actually install this stuff. I am trying to use the Supabase integration.

**Comment by Samuel-Martineau** [comment]
@ethanfox I believe datasource plugins simply can't be installed on a cloud instance of Budibase for security reasons

**Comment by joebudi** [comment]
@Samuel-Martineau is correct.
